node ('openshift-jenkins-pipeline') {

    stage('code-checkout') {
        git url:"https://github.com/UKCloud/openshift-heat.git"
    }

    stage('setup OpenStack credentials') {
        sh "echo OS_PASSWORD=`oc get secrets openstack --template='{{ .data.password }}' | base64 --decode` | tee -a openstack_rc.sh"
        sh "echo OS_USERNAME=`oc get secrets openstack --template='{{ .data.username }}' | base64 --decode` | tee -a openstack_rc.sh"
        sh "echo OS_TENANT_ID=`oc get configmap openstack-config --template='{{ .data.openstack_project_id }}'` | tee -a openstack_rc.sh"
        sh "echo OS_AUTH_URL=`oc get configmap openstack-config --template='{{ .data.openstack_url }}'` | tee -a openstack_rc.sh"
    }

    stage('build HEAT environment') {
        sh 'cat openstack_rc.sh'
        sh 'source ./openstack_rc.sh ; echo \$OS_AUTH_URL ; openstack catalog list'
    }
}
