apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: openstackclient-jenkins-slave
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: jenkins-slave-base-rhel7
  spec:
    tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      role: jenkins-slave
    name: ${NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: ${NAME}
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: jenkins-slave-base-rhel7:latest
      type: Docker
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: ${NAME}-pipeline
    name: ${NAME}-pipeline
  spec:
    nodeSelector: null
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: ${PIPELINE_CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: jenkins-slave-base-rhel7:latest 
    - type: ConfigChange
parameters:
- description: The name assigned to the objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: openstackclient-jenkins-slave
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/charliejllewellyn/openshift-jenkins-pipeline.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
  value: docker/openstack
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Pipeline Context Directory
  name: PIPELINE_CONTEXT_DIR
  value: jenkins-pipelines/openstack
- description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
