node {

    stage('build') {
        openshiftBuild(buildConfig: 'openshift-jenkins-pipeline', showBuildLogs: 'true')
    }

}

node ('openshift-jenkins-pipeline') {

    stage('test') {
        sh('openstack -h')
    }

}

node {

    stage('promote') {
        openshiftTag(sourceStream: 'openshift-jenkins-pipeline', sourceTag: 'latest', destinationNamespace: 'build-openshift-pre-prod', destinationStream: 'openshift-jenkins-pipeline', destinationTag: 'latest')
    }

}
